// @ts-check
export const MESSAGE_ADD = 'MESSAGE_ADD',
    // Connection
    CONNECTION_ESTABLISHED = 'CONNECTION_ESTABLISHED',
    CONNECTION_ATTEMPTED = 'CONNECTION_ATTEMPTED',
    CONNECTION_DROPPED = 'CONNECTION_DROPPED',
    CONNECTION_LISTENING = 'CONNECTION_LISTENING';
