// @ts-check
/**
 * @ignore
 */
export const MESSAGE_ADD = 'MESSAGE_ADD',
    MESSAGE_SEND = 'MESSAGE_SEND',
    MESSAGE_RECEIVE = 'MESSAGE_RECEIVE',
    MESSAGE_QUEUE = 'MESSAGE_QUEUE',
    // Connection
    CONNECTION_ESTABLISHED = 'CONNECTION_ESTABLISHED',
    CONNECTION_ATTEMPTED = 'CONNECTION_ATTEMPTED',
    CONNECTION_DROPPED = 'CONNECTION_DROPPED',
    CONNECTION_LISTENING = 'CONNECTION_LISTENING';
