// @ts-check
export const ADD_MESSAGE = 'ADD_MESSAGE',
    // Connection
    CONNECTION_ESTABLISHED = 'CONNECTION_ESTABLISHED',
    CONNECTION_ATTEMPTED = 'CONNECTION_ATTEMPTED',
    CONNECTION_DROPPED = 'CONNECTION_DROPPED',
    CONNECTION_LISTENING = 'CONNECTION_LISTENING';
